# ==============================================================================
# CODEVERITUS SYSTEM CORE MODULE
# ==============================================================================
# File: front-end/nginx.conf
# Author: ABHIMANYU993
# Email: abhimanyubadiger1001@gmail.com
# Project: Codeveritus - AI vs Human Code Classifier
# Description: Modular component containing system configuration or script details.
# ==============================================================================

server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  # This try_files directive is the key to making React Router work correctly.
  location / {
    try_files $uri /index.html;
  }
}